# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cacclcheck.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 399)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 301, 91))
        font = QtGui.QFont()
        font.setFamily("a_AlgeriusCapsNr")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 217), stop:0.166 rgba(255, 255, 0, 215), stop:0.333 rgba(0, 255, 0, 220), stop:0.5 rgba(0, 255, 255, 223), stop:0.666 rgba(0, 0, 255, 223), stop:0.833 rgba(255, 0, 255, 218), stop:1 rgba(255, 0, 0, 218));\n"
"color: rgb(85, 0, 0);")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 300, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setUnderline(True)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButtonR = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonR.setGeometry(QtCore.QRect(80, 300, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButtonR.setFont(font)
        self.pushButtonR.setStyleSheet("background-color: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.412935 rgba(37, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.497512 rgba(255, 0, 0, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(155, 243, 255, 255), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(85, 0, 0);\n"
"")
        self.pushButtonR.setObjectName("pushButtonR")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(0, 230, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 230, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 160, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 162, 164);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 90, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setItalic(False)
        font.setUnderline(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(80, 90, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(150, 90, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 90, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 160, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 162, 164);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_Plus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Plus.setGeometry(QtCore.QRect(220, 230, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_Plus.setFont(font)
        self.pushButton_Plus.setStyleSheet("background-color: rgb(197, 255, 255);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:27.5, stop:0 rgba(102, 11, 11, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(105, 0, 0, 255));\n"
"color: rgb(52, 0, 0);")
        self.pushButton_Plus.setObjectName("pushButton_Plus")
        self.pushButton_Minus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Minus.setGeometry(QtCore.QRect(150, 230, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_Minus.setFont(font)
        self.pushButton_Minus.setStyleSheet("color: rgb(85, 0, 0);\n"
"background-color: rgb(197, 255, 255);\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.593, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 117), stop:0.52 rgba(0, 0, 0, 0), stop:0.565 rgba(82, 121, 76, 33), stop:0.65 rgba(159, 235, 148, 64), stop:0.721925 rgba(255, 238, 150, 129), stop:0.77 rgba(255, 128, 128, 204), stop:0.89 rgba(191, 128, 255, 64), stop:1 rgba(0, 0, 0, 0));\n"
"")
        self.pushButton_Minus.setObjectName("pushButton_Minus")
        self.pushButton_Del = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Del.setGeometry(QtCore.QRect(150, 160, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_Del.setFont(font)
        self.pushButton_Del.setStyleSheet("background-color: rgb(197, 255, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(9, 41, 4, 255), stop:0.0646766 rgba(2, 79, 0, 255), stop:0.169154 rgba(50, 147, 22, 255), stop:0.263682 rgba(236, 179, 0, 255), stop:0.432836 rgba(243, 61, 34, 255), stop:0.616915 rgba(121, 75, 255, 255), stop:0.781095 rgba(164, 255, 244, 255), stop:0.890547 rgba(104, 222, 71, 255), stop:1 rgba(135, 81, 60, 255));")
        self.pushButton_Del.setObjectName("pushButton_Del")
        self.pushButton_Ymn = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Ymn.setGeometry(QtCore.QRect(220, 300, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.pushButton_Ymn.setFont(font)
        self.pushButton_Ymn.setStyleSheet("background-color: rgb(197, 255, 255);\n"
"color: rgb(85, 0, 0);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(133, 84, 34, 255), stop:1 rgba(97, 97, 97, 255));\n"
"color: rgb(40, 0, 0);")
        self.pushButton_Ymn.setObjectName("pushButton_Ymn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.addfunction()
        
        self.eq=False
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Каккулятор"))
        self.label.setText(_translate("MainWindow", "0"))
        self.pushButton.setText(_translate("MainWindow", "0"))
        self.pushButtonR.setText(_translate("MainWindow", "="))
        self.pushButton_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_Plus.setText(_translate("MainWindow", "+"))
        self.pushButton_Minus.setText(_translate("MainWindow", "-"))
        self.pushButton_Del.setText(_translate("MainWindow", "//"))
        self.pushButton_Ymn.setText(_translate("MainWindow", "*"))
    def addfunction(self):
        self.pushButton.clicked.connect(lambda: self.write(self.pushButton.text()))
        self.pushButton_1.clicked.connect(lambda: self.write(self.pushButton_1.text()))
        self.pushButton_2.clicked.connect(lambda: self.write(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(lambda: self.write(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(lambda: self.write(self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(lambda: self.write(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(lambda: self.write(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(lambda: self.write(self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(lambda: self.write(self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(lambda: self.write(self.pushButton_9.text()))
        self.pushButton_Plus.clicked.connect(lambda: self.write(self.pushButton_Plus.text()))
        self.pushButton_Del.clicked.connect(lambda: self.write(self.pushButton_Del.text()))
        self.pushButton_Minus.clicked.connect(lambda: self.write(self.pushButton_Minus.text()))
        self.pushButton_Ymn.clicked.connect(lambda: self.write(self.pushButton_Ymn.text()))
        self.pushButtonR.clicked.connect(self.result)
    
    def write(self,number):
        if self.label.text()=="0" or self.eq:
            self.label.setText(number)
            self.eq=False
        else:
             self.label.setText(self.label.text()+number)
    def result(self):
        res=eval(self.label.text())
        self.label.setText("Ответ епт"+" "+str(res))
        self.eq=True


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
